version: 0.2

phases:

  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip -O terraform.zip
      - wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -O tflint.zip
      - wget https://github.com/liamg/tfsec/releases/latest/download/tfsec-linux-amd64 -O tfsec
      - unzip terraform.zip
      - unzip tflint.zip
      - chmod +x terraform tflint tfsec
      - printf "\nbucket = \"%s\"\nkms_key_id = \"%s\"\n" "$BUCKET" "$KMS_KEY_ID" >> config/prod/backend.conf
      - printf "acl = \"bucket-owner-full-control\"" >> config/prod/backend.conf
      - cat config/prod/backend.conf

  build:
    commands:
      - echo "Initialising Terraform"
      - ./terraform init -backend-config=config/prod/backend.conf
      - echo "Linting..."
      - ./tflint . --module
      - echo "Checking for security flaws" 
      - ./tfsec .

  post_build:
    commands:
      - echo "tflint and tfsec found no errors. Terraform verification complete."
