version: 0.2

phases:
  install:
    commands:
      - echo Execute install
      - wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_darwin_amd64.zip -O terraform.zip
      - unzip terraform.zip
      
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=`curl --silent 169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`curl --silent 169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.SecretAccessKey'`
      - export AWS_SESSION_TOKEN=`curl --silent 169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.Token'`
      - echo Execute Build
      - ./terraform init
      - ./terraform plan
